- block:
  
  - include_tasks: packages.yml
  - include_tasks: settings.yml
  - include_tasks: ruby.yml
  - include_tasks: terminal.yml


# This install the DMG based applications
- name: "Install Google Chrome"
  include_tasks: dmg-install.yml
  vars:
    appName: GoogleChrome
    dmgURL: https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg

- name: "Install Herd"
  include_tasks: dmg-install.yml
  vars:
    appName: Herd
    dmgURL: https://herd.laravel.com/download

- name: "Install PhpStorm"
  include_tasks: dmg-install.yml
  vars:
    appName: PhpStorm
    dmgURL: https://download.jetbrains.com/webide/PhpStorm-2024.3.1.dmg

- name: "Install Balena Etcher"
  include_tasks: dmg-install.yml
  vars:
    appName: BalenaEtcher
    dmgURL: https://github.com/balena-io/etcher/releases/download/v1.19.25/balenaEtcher-1.19.25-x64.dmg

# not working
# This install the PKG based applications
#- name: "AWS CLI"
#  include_tasks: pkg-install.yml
#  vars:
#    install_path: /usr/local/bin/aws
#    pkgName: AWSCLIV2.pkg
#    pkgURL: https://awscli.amazonaws.com/AWSCLIV2.pkg

