- name: Update Macports and the ports tree
  community.general.macports:
    selfupdate: true
    upgrade: true
  changed_when: false
  when: ansible_distribution == "MacOSX" and ansible_distribution_major_version not in ["14", "15"]
  tags: macports

- name: install various macports
  community.general.macports:
    name: "{{ ports }}"
  vars:
    ports:
    - wget
    - htop
    - nmap
    - coreutils
    - ImageMagick7
    - ffmpeg
    - yt-dlp
    - gnupg2
    - tree
    - inetutils
    - tmux
    - pandoc
    - lynx
    - emacs
    - aspell
    - mtr
    - mc
    - neofetch
    - texlive-latex-extra
    - bat
    - neovim
    - rclone
    - 7zip
    - php83
    - certbot
    - ruby33
    - ruby-build
    - rbenv
    - prettyping
    - ipcalc
    - tree
    - apg
    - pstree
 when: ansible_distribution == "MacOSX" and ansible_distribution_major_version not in ["14", "15"]
