- name: Update Macports and the ports tree
  community.general.macports:
    selfupdate: true
    upgrade: true
  changed_when: false

- name: install various macports
  community.general.macports:
    name: "{{ ports }}"
  vars:
    ports:
    - wget
    - htop
    - nmap
    - coreutils
    - ImageMagick7
    - ffmpeg
    - yt-dlp
    - gnupg2
    - tree
    - inetutils
    - tmux
    - pandoc
    - lynx
    - emacs
    - aspell
    - mtr
    - mc
    - neofetch
    - texlive-latex-extra
    - bat
    - neovim
    - rclone
    - 7zip
    - php83
    - certbot
    - ruby33
    - ruby-build
    - rbenv
    - prettyping
    - ipcalc
    - tree
    - apg
    - pstree

# Not working even with timeout.
#Install VSCode. NOTE - No longer supported on Monterey
#- name: Install Visual Studio Code
#  get_url: 
#    url: "https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal" 
#    dest: "/Applications/Visual Studio Code.app"
#  when: ansible_distribution_major_version in ["13", "14", "15"]
