- name: Install ruby {{ ruby_version }}
  become_user: "{{ user_name }}"
  command: rbenv install --skip-existing {{ ruby_version }}
  changed_when: false

- name: Set ruby global default as {{ ruby_version }}
  become_user: "{{ user_name }}"
  command: rbenv global {{ ruby_version }}
  changed_when: false

- name: Set ruby local default as {{ ruby_version }}
  become_user: "{{ user_name }}"
  command: chdir=~/ rbenv local {{ ruby_version }}
  changed_when: false
