- name: Install ruby 2.6.1
  become_user: "{{ user_name }}"
  command: rbenv install --skip-existing 2.6.1
  changed_when: false

- name: Set ruby global default as 2.6.1
  become_user: "{{ user_name }}"
  command: rbenv global 2.6.1
  changed_when: false

- name: Set ruby local default as 2.6.1
  become_user: "{{ user_name }}"
  command: chdir=~/ rbenv local 2.6.1
  changed_when: false
