# These are all of my custom mac settings.


# Configure the default screenshot location
- name: configure screenshots folder
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: ~/Downloads
  become_user: "{{ user_name }}"

# Not even sure if this works but not trying to be messy and insecure.
- name: Avoid creating .DS_Store files
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  become_user: "{{ user_name }}"

# Disable system notifications. Not sure if this works either
- name: Disable system notifications
  community.general.osx_defaults:
    path: /Library/Preferences/.GlobalPreferences
    domain: NSUserNotificationCenter
    key: enabled
    value: false
  
# Setup 3 finger drag. I rebooted but relogin probably and it kicks in
- name: Enable 3 finger drag
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: true
  become_user: "{{ user_name }}"


